import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { cn } from '@/shared/lib/utils';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const suite = localFont({
  src: '../../public/fonts/suite-variable.woff2',
  variable: '--font-suite',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={cn('h-full', 'antialiased', suite.variable)}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
